import React,{useEffect,useState} from 'react'
import './ApiAudit.css'
export default function MockApiReview(){
 const [report,setReport]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(37),[all,setAll]=useState(false),[filter,setFilter]=useState('')
 useEffect(()=>{const controller=new AbortController();fetch('/__audit/mock-contract.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Run npm run mock:verify:all to generate the response report.');return r.json()}).then(setReport).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[])
 const screen=report?.screens.find(s=>s.id===selected),captures=report?.captures||[],rows=all?captures.filter(c=>!filter||`${c.method} ${c.path} ${c.status}`.toLowerCase().includes(filter.toLowerCase())):(screen?.capture_ids||[]).map(id=>captures.find(c=>c.id===id))
 return <main className="api-audit"><header><div><span className="audit-eyebrow">LOCAL MOCK API · VERIFIED HTTP RESPONSES</span><h1>Kidsverse+ · 62-screen API review</h1><p>Captured requests and JSON responses from an isolated local database. Credentials redacted.</p></div><div><a href="/mock-demo">Interactive screens</a> · <a href="/api/v1/openapi.json" target="_blank" rel="noreferrer">Full API contract</a></div></header>
 <div className="audit-summary"><span><b>{report?.verified_operations||'—'}</b> API operations</span><span><b>{report?.screens.length||'—'}</b> screens</span><span><b>{captures.length||'—'}</b> HTTP captures</span><span className="good">{report?.restart_verified?'Restart / resume verified':''}</span><small>{report?new Date(report.generated_at).toLocaleString():error||'Loading responses…'}</small></div>
 {report&&<div className="audit-workspace"><nav aria-label="Screen API responses">{report.screens.map(s=><button key={s.id} aria-current={!all&&selected===s.id?'page':undefined} onClick={()=>{setSelected(s.id);setAll(false)}}>{String(s.id).padStart(2,'0')} {s.name}</button>)}</nav><section className="audit-detail"><div className="audit-toolbar"><h2>{all?'All captured API calls':`${screen.id} · ${screen.name}`}</h2><button onClick={()=>setAll(v=>!v)}>{all?'Screen calls':'All calls / errors'}</button>{all&&<input aria-label="Filter API calls" placeholder="Method, path or status…" value={filter} onChange={e=>setFilter(e.target.value)}/>}<a href="/__audit/mock-contract.json" download="Kidsverse-all-62-mock-responses.json">Download JSON</a></div><div style={{overflow:'auto',padding:16}}>
 {!all&&<p className="audit-note">{screen.note}</p>}
 {!rows.length&&<p className="audit-empty">No API request is needed for this local UI screen.</p>}
 {rows.map(c=><section className="audit-response" key={c.id}><h3><span className={c.status<400?'good':'bad'}>{c.status}</span> {c.method} {c.path}</h3><small>Capture {c.id} · {c.origin} · actual HTTP response</small><div className="audit-columns"><section style={{paddingRight:12}}><h4>Request JSON</h4><pre>{c.request===null?'No request body':JSON.stringify(c.request,null,2)}</pre></section><section><h4>Response JSON</h4><pre>{JSON.stringify(c.response,null,2)}</pre></section></div></section>)}
 </div></section></div>}
 </main>
}
